# Generated by Django 5.0.4 on 2025-03-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='evaluated_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='evaluated/'),
        ),
    ]
