# Generated by Django 5.0.4 on 2025-03-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_evaluated_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='encrypted_metadata_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
